version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    expose:
      - "8000"
    volumes:
      - app_static:/code/static
      - app_media:/code/media
      - /var/log/lockers-admin:/var/log
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    env_file:
      - ./.env
    command: runserver.sh

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    expose:
      - "8000"
    depends_on:
      - app
      - redis
    links:
      - app
      - redis
    env_file:
      - ./.env
    command: celery_worker.sh

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - app_static:/code/static
      - app_media:/code/media
    links:
      - app
    depends_on:
      - app

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    restart: always
    volumes:
      - ./etc/postgres_data:/var/lib/postgresql/data
      - ./etc/backups:/backups
    env_file:
      - ./.env

volumes:
  app_static:
  app_media:
  postgres_data:
  postgres_backup:
